baseurl = "https://tomleesm.github.io"
title = "Tom 除錯中"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Tom"
  info = "程式園丁一枚"
  description = "Tom 的部落格，主要放閱讀程式設計書籍的筆記"
  keywords = "blog,php,javascript"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tomleesm/"
#[[params.social]]
#  name = "Gitlab"
#  icon = "fa-brands fa-gitlab fa-2x"
#  weight = 2
#  url = "https://gitlab.com/johndoe/"
#[[params.social]]
#  name = "Twitter"
#  icon = "fa-brands fa-x-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
